Vagrant.configure("2") do |config|

  # =========================
  # WEB01 - Ubuntu 20.04
  # =========================
  config.vm.define "web01" do |web01|

    web01.vm.box = "ubuntu/focal64"

    web01.vm.hostname = "web01"

    web01.vm.network "private_network",
      ip: "192.168.56.11"

    web01.vm.provider "virtualbox" do |vb|
      vb.name = "web01"
      vb.memory = 1024
      vb.cpus = 1
    end

  end


  # =========================
  # WEB02 - Ubuntu 20.04
  # =========================
  config.vm.define "web02" do |web02|

    web02.vm.box = "ubuntu/focal64"

    web02.vm.hostname = "web02"

    web02.vm.network "private_network",
      ip: "192.168.56.12"

    web02.vm.provider "virtualbox" do |vb|
      vb.name = "web02"
      vb.memory = 1024
      vb.cpus = 1
    end

  end


  # =========================
  # DB01 - CentOS 7
  # =========================
  config.vm.define "db01" do |db01|

    db01.vm.box = "centos/7"

    db01.vm.hostname = "db01"

    db01.vm.network "private_network",
      ip: "192.168.56.13"

    db01.vm.provider "virtualbox" do |vb|
      vb.name = "db01"
      vb.memory = 1024
      vb.cpus = 1
    end

    # Provisioning
    db01.vm.provision "shell", inline: <<-SHELL

      echo "Configurando DB01..."

      yum update -y


      
      yum install -y wget unzip mariadb-server

      systemctl enable mariadb
      systemctl start mariadb

      echo "DB01 configurado com sucesso!"

    SHELL

  end

end